image:
  repository: tooljet/tooljet-ce
  pullPolicy: IfNotPresent

apps:
  tooljet:
    service:
      type: ClusterIP
      host: "http://localhost"
    deployment:
      resources:
        requests:
          memory: "1000Mi"
          cpu: "1000m"
        limits:
          memory: "2000Mi"
          cpu: "2000m"
    hpa:
      min: 1
      max: 1
      threshhold:
        cpu: 0.75
        ram: 768Mi
    secret:
      name: tooljet-server
      data:
        pg_user: "postgresql"
        pg_password: "postgresql"
        pg_db: "tooljet"
        lockbox_key: "0123456789ABCDEF"
        secret_key_base: "0123456789ABCDEF"

postgresql:
  enabled: true
  postgresqlExtendedConf:
    maxConnections: 1024
  replication:
    enabled: false
  auth:
    postgresPassword: "postgres"
    username: "postgresql"
    password: "postgresql"
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: ""
